const { ROUTE_TARGETS, PUBLIC_RULES, PROTECTED_RULES } = require("./routes");

const FRONTEND_ENDPOINTS = Object.freeze([
  {
    method: "POST",
    path: "/auth/signup",
    service: "user",
    auth: "public",
    description: "Create a new account.",
  },
  {
    method: "POST",
    path: "/auth/login",
    service: "user",
    auth: "public",
    description: "Authenticate and receive JWT token.",
  },
  {
    method: "POST",
    path: "/auth/forgot-password",
    service: "user",
    auth: "public",
    description: "Request password reset OTP.",
  },
  {
    method: "POST",
    path: "/auth/reset-password/otp",
    service: "user",
    auth: "public",
    description: "Reset password using OTP flow.",
  },
  {
    method: "POST",
    path: "/auth/reset-password",
    service: "user",
    auth: "protected",
    description: "Reset password for authenticated user.",
  },
  {
    method: "GET",
    path: "/auth/session",
    service: "user",
    auth: "protected",
    description: "Validate current token session.",
  },
  {
    method: "GET",
    path: "/auth/users",
    service: "user",
    auth: "role",
    roles: ["admin"],
    description: "List users for admin dashboard.",
  },
  {
    method: "POST",
    path: "/users",
    service: "user",
    auth: "role",
    roles: ["admin"],
    description: "Create user by admin.",
  },
  {
    method: "GET",
    path: "/users/:id",
    service: "user",
    auth: "protected",
    description: "Get single user profile.",
  },
  {
    method: "PUT",
    path: "/users/:id",
    service: "user",
    auth: "protected",
    description: "Update profile (owner or admin enforced downstream).",
  },
  {
    method: "DELETE",
    path: "/users/:id",
    service: "user",
    auth: "protected",
    description: "Delete profile (owner or admin enforced downstream).",
  },
  {
    method: "GET",
    path: "/categories",
    service: "product",
    auth: "public",
    description: "List product categories.",
  },
  {
    method: "POST",
    path: "/categories",
    service: "product",
    auth: "role",
    roles: ["admin"],
    description: "Create category.",
  },
  {
    method: "GET",
    path: "/products",
    service: "product",
    auth: "public",
    description: "List products.",
  },
  {
    method: "GET",
    path: "/products/:id",
    service: "product",
    auth: "public",
    description: "Get product details by id.",
  },
  {
    method: "POST",
    path: "/products",
    service: "product",
    auth: "role",
    roles: ["admin", "supplier"],
    description: "Create product.",
  },
  {
    method: "GET",
    path: "/inventory/:productId",
    service: "inventory",
    auth: "public",
    description: "Get product stock snapshot.",
  },
  {
    method: "PUT",
    path: "/inventory/:productId/stock",
    service: "inventory",
    auth: "role",
    roles: ["admin", "supplier"],
    description: "Set product stock quantity.",
  },
  {
    method: "GET",
    path: "/search/products",
    service: "search",
    auth: "public",
    description: "Search products with filters/pagination.",
  },
  {
    method: "*",
    path: "/carts/*",
    service: "cart",
    auth: "protected",
    description: "Cart operations for authenticated users.",
  },
  {
    method: "*",
    path: "/orders/*",
    service: "order",
    auth: "protected",
    description: "Order lifecycle operations.",
  },
  {
    method: "*",
    path: "/payments/*",
    service: "payment",
    auth: "protected",
    description: "Payment operations.",
  },
  {
    method: "*",
    path: "/notifications/*",
    service: "notification",
    auth: "protected",
    description: "Notification inbox operations.",
  },
  {
    method: "GET",
    path: "/audit/logs",
    service: "audit",
    auth: "role",
    roles: ["admin"],
    description: "Audit logs list for admins.",
  },
  {
    method: "GET",
    path: "/audit/logs/me",
    service: "audit",
    auth: "protected",
    description: "Current user activity logs.",
  },
]);

const mapRule = (rule) => ({
  method: rule.method,
  pattern: rule.pattern.source,
  roles: Array.isArray(rule.roles) ? rule.roles : [],
});

const buildFrontendCatalog = ({
  port,
  runtimeBaseUrl,
  exposeInternalRoutes,
  cors,
}) => ({
  generatedAt: new Date().toISOString(),
  gateway: {
    service: "api-gateway",
    port,
    runtimeBaseUrl,
    exposeInternalRoutes: Boolean(exposeInternalRoutes),
  },
  cors,
  routeTargets: ROUTE_TARGETS.map(({ prefix, service }) => ({ prefix, service })),
  authRules: {
    public: PUBLIC_RULES.map(mapRule),
    protected: PROTECTED_RULES.map(mapRule),
  },
  endpoints: FRONTEND_ENDPOINTS,
});

module.exports = {
  buildFrontendCatalog,
};
